version: '3.9'

name: myapi

services:
  api:
    container_name: helloworld_1
    build: 
      context: ./compose_db
      dockerfile: Dockerfile.dev
    depends_on:
      - postgres_db
    ports:
      - "8000:8000"
    networks:
      - my_api_net
    volumes:
      - ./compose_db:/code/

  postgres_db:
    image:  postgres:latest
    restart: always
    container_name: PostgresCont
    environment:
      - POSTGRES_USER=fatima
      - POSTGRES_PASSWORD=my_password
      - POSTGRES_DB=mydatabase
    ports:
      - "5433:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - my_api_net

volumes:
  postgres_db:
    driver: local

networks:
  my_api_net: 